export default {
    LOAD_BOOK_LIST: 'LOAD_BOOK_LIST',
    DELETE: 'DELETE',

    //User actions//
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOAD_USER: 'LOAD_USER',
    ADD_FAVORITE_BOOK: 'ADD_FAVORITE_BOOK'
};
