export default {
    //Books actions//
    LOAD_BOOK_LIST: 'LOAD_BOOK_LIST',
    LOAD_BOOK: 'LOAD_BOOK',

    //User actions//
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOAD_USER: 'LOAD_USER',
    ADD_FAVORITE_BOOK: 'ADD_FAVORITE_BOOK',
    DELETE_FAVORITE_BOOK: 'DELETE_FAVORITE_BOOK',

    //Search actions//
    SEARCH_BOOKS: 'SEARCH_BOOKS'
};
